import type { Metadata } from "next";
import "./globals.css";
// import ButtonComponent from "@/components/ButtonComponent";
import { NavbarComponent } from "@/components/nav/NavbarComponent";
import { FooterComponent } from "@/components/nav/FooterComponent";
// import styles from './style.module.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <NavbarComponent/>
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
