import type { Metadata } from "next";
import "./globals.css";
import localfont from 'next/font/local'
// import ButtonComponent from "@/components/ButtonComponent";
// import { NavbarComponent } from "@/components/(landing)/nav/NavbarComponent";
import { FooterComponent } from "@/components/(landing)/nav/FooterComponent";
import React from "react";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { NavbarComponent } from "@/components/(landing)/nav/NavbarComponent";
import { routing } from "@/i18n/routing";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// kantumruy_font 
const kantumruy_font = localfont({
  src: '../../../public/fonts/KantumruyPro-SemiBold.ttf',
  variable: '--font-kantumruy',
  display: 'swap',
  preload: true,
  fallback: ['sans']
})

// lexend_font
const lexend_font = localfont({
  src: '../../../public/fonts/Lexend-Regular.ttf',
  variable: '--font-lexend',
  display: 'swap'
})

export default async function RootLayout({
  children,
  modal,
  params
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
  params: Promise<{ locale: string }>
}>) {

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={(await params).locale} className={`${kantumruy_font.variable} ${lexend_font.variable}`}>
      <body
      >
        <NextIntlClientProvider>
          <NavbarComponent/>
          {children}
          {modal}
          <FooterComponent />

        </NextIntlClientProvider>

      </body>
    </html>
  );
}
